### ISSUE TITLE
Compilation fails with Erlang 24

### ISSUE THREAD

**Issue by richmeta** [ndac-todoroki/elixir-id3#7]
Hi,

```
❯ mix deps.compile id3
==> id3
Compiling NIF crate :id3 (native/id3)...
    Updating crates.io index
 Downloading crates ...
  Downloaded backtrace v0.3.55
  Downloaded object v0.22.0
   Compiling object v0.22.0
   Compiling rustler_codegen v0.21.1
   Compiling backtrace v0.3.55
   Compiling failure v0.1.8
   Compiling which v2.0.1
   Compiling rustler v0.21.1
error: failed to run custom build command for `rustler v0.21.1`

Caused by:
  process didn't exit successfully: `/home/richard/workspace/emymp3/_build/dev/rustler_crates/id3/release/build/rustler-02542dc7da0844ff/build-script-build` (exit code: 101)
  --- stderr
  thread 'main' panicked at 'Erlang version 2.16 not handled, please file a a bug report.', /home/richard/.cargo/registry/src/github.com-1ecc6299db9ec823/rustler-0.21.1/build.rs:50:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
could not compile dependency :id3, "mix compile" failed. You can recompile this dependency with "mix deps.compile id3", update it with "mix deps.update id3" or clean it with "mix deps.clean id3"
** (RuntimeError) Rust NIF compile error (rustc exit code 101)
    (rustler 0.21.1) lib/mix/tasks/compile.rustler.ex:68: Mix.Tasks.Compile.Rustler.compile_crate/1
    (elixir 1.11.3) lib/enum.ex:1411: Enum."-map/2-lists^map/1-0-"/2
    (rustler 0.21.1) lib/mix/tasks/compile.rustler.ex:15: Mix.Tasks.Compile.Rustler.run/1
    (mix 1.11.3) lib/mix/task.ex:394: Mix.Task.run_task/3
    (mix 1.11.3) lib/mix/tasks/compile.all.ex:90: Mix.Tasks.Compile.All.run_compiler/2
    (mix 1.11.3) lib/mix/tasks/compile.all.ex:70: Mix.Tasks.Compile.All.compile/4
    (mix 1.11.3) lib/mix/tasks/compile.all.ex:57: Mix.Tasks.Compile.All.with_logger_app/2
    (mix 1.11.3) lib/mix/tasks/compile.all.ex:35: Mix.Tasks.Compile.All.run/1
```

If you look at https://github.com/rusterlium/rustler/issues/359 it appears there's a later version of rustler that supports it. 

rustc 1.52.1
Erlang/OTP 24
Elixir 1.11.3

**Comment by ndac-todoroki** [comment]
Thanks for the report!
Seems just updating the Rustler version doesn't fix this, since macros inside the Rust module part of Rustler has changed; some code needs to be changed.
I'll be working for this.
